### ISSUE TITLE
Support need : [161125]アキウソ -The only neat thing to do-

### ISSUE THREAD

**Issue by Eguni** [mireado/ITHVNR_kor#3]
# Information
Engine : malie
Text Output function : ExtTextOutW-GDI32.dll
Old H-Code : /HQ18@5980

# Note

[2016.12.04 16:06]
![bandicam 2016-12-04 16-01-48-672](https://cloud.githubusercontent.com/assets/12514940/20864625/2f0270ca-ba3c-11e6-8114-7e5230a99f5d.jpg)

ITHVNR seems to hook dummy pointer data.

**Comment by mireado** [comment]
Try this version of ITHVNR
http://mireado.blog.me/220842297353

OK, I'll update code soon. >_<

**Comment by Eguni** [comment]
Thnks! :)
